<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tsekap_seqno_det', function (Blueprint $table) {
            $table->string('SEQ_NAME', 25)->nullable()->comment('SEQUENCE NAME');
            $table->string('seq_code', 25)->nullable();
            $table->integer('LAST_VALUE')->nullable()->comment('CURRENT SEQUENCE NUMBER OF GENERATED CODE');
            $table->dateTime('LAST_GEN_DATE')->nullable()->comment('LAST GENERATION DATE');
            $table->string('LAST_GEN_BY', 20)->nullable()->comment('LAST GENERATED BY');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tsekap_seqno_det');
    }
};
